---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Check Sudo Password
      command: ls
      become: yes
      become_method: sudo

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=caskroom/cask

    - name: Tap Caskroom/Versions
      homebrew_tap: tap=caskroom/versions

    - name: Tap completions
      homebrew_tap: tap=homebrew/completions

    - name: Install Caskroom
      homebrew: name=brew-cask state=latest

    - name: Change user shell to zsh
      command: dscl . -create /Users/$USER UserShell /bin/zsh
      become: yes
      become_method: sudo

    - name: Install brew apps
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker-completion
        - docker-compose
        - docker-compose-completion
        - docker-machine
        - go
        - homebrew/dupes/less
        - https://raw.githubusercontent.com/choppsv1/homebrew-term24/master/tmux.rb
        - neovim/neovim/neovim
        - pip-completion
        - pyenv
        - vagrant-completion
        - zsh-completion

    - name: Install cask apps
      homebrew_cask:
        name: "{{ item }}"
        state: latest
      with_items:
        - avast
        - docker
        - dropbox
        - firefox
        - google-chrome
        - iterm2-nightly
        - sketch
        - sketch-tool
        - sketch-toolbox
        - skitch
        - slack
        - the-unarchiver
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Install Pythons
      command: pyenv install "{{ item }}"
      with_items:
        - 2.7.11
        - 3.5.1
      environment:
        PYENV_ROOT="$HOME/.pyenv"
